<?php

/**
 * BaseEmail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $adresse
 * @property string $name
 * @property boolean $ist_bestaetigt
 * 
 * @method string  getAdresse()        Returns the current record's "adresse" value
 * @method string  getName()           Returns the current record's "name" value
 * @method boolean getIstBestaetigt()  Returns the current record's "ist_bestaetigt" value
 * @method Email   setAdresse()        Sets the current record's "adresse" value
 * @method Email   setName()           Sets the current record's "name" value
 * @method Email   setIstBestaetigt()  Sets the current record's "ist_bestaetigt" value
 * 
 * @package    tgnews
 * @subpackage model
 * @author     Frank Mattes
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('email');
        $this->hasColumn('adresse', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('ist_bestaetigt', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}