<?php

/**
 * BaseNewsletter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $text
 * @property string $headline
 * @property boolean $ist_gesendet
 * @property string $beschreibung
 * @property User $User
 * 
 * @method integer    getUserId()       Returns the current record's "user_id" value
 * @method string     getText()         Returns the current record's "text" value
 * @method string     getHeadline()     Returns the current record's "headline" value
 * @method boolean    getIstGesendet()  Returns the current record's "ist_gesendet" value
 * @method string     getBeschreibung() Returns the current record's "beschreibung" value
 * @method User       getUser()         Returns the current record's "User" value
 * @method Newsletter setUserId()       Sets the current record's "user_id" value
 * @method Newsletter setText()         Sets the current record's "text" value
 * @method Newsletter setHeadline()     Sets the current record's "headline" value
 * @method Newsletter setIstGesendet()  Sets the current record's "ist_gesendet" value
 * @method Newsletter setBeschreibung() Sets the current record's "beschreibung" value
 * @method Newsletter setUser()         Sets the current record's "User" value
 * 
 * @package    tgnews
 * @subpackage model
 * @author     Frank Mattes
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNewsletter extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('newsletter');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('text', 'string', 500, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 500,
             ));
        $this->hasColumn('headline', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('ist_gesendet', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('beschreibung', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}